'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10terms will be:
1,2,3,5,8,13,21,34,55,89,…

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def fib(n):

    if n in [1,2]:
        return 1

    return (fib(n-1) + fib(n-2))
sum = 0    
for i in range(2,1000):
    if fib(i) < 4000000:
        if (fib(i)%2) == 0:
            sum += fib(i)
    else:
        break
print(sum)